name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      
      - name: Install server dependencies
        run: |
          cd server
          npm ci
      
      - name: Install client dependencies
        run: |
          cd client
          npm ci
      
      - name: Run frontend linting
        run: |
          cd client
          npm run lint
  
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
         
      
      - name: Prepare backend
        run: |
          cd server
          npm ci
          # Create .env.production file if needed
          # echo "NODE_ENV=production" > .env.production
      
      - name: Build frontend
        run: |
          cd client
          npm ci
          npm run build
      
    #   - name: Archive backend
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: backend-files
    #       path: server/
    #       retention-days: 3
          
    #   - name: Archive frontend build
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: frontend-build
    #       path: client/dist
    #       retention-days: 3
  

  deploy-docker:
    name: Push to Docker Hub
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

         # --- Build & Push CLIENT image ---

      - name: Build and tag Docker image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/todo-client:latest ./client

      - name: Push Docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/todo-client:latest

          # --- Build & Push SERVER image ---
      - name: Build and tag Docker image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/todo-server:latest ./server

      - name: Push Docker image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/todo-server:latest

        
  deploy:
    name: Deploy to Render
    needs: deploy-docker
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
    #   - name: Download backend files
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: backend-files
    #       path: server/
      
    #   - name: Download frontend files
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: frontend-build
    #       path: client/dist
      
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          github_token: ${{ secrets.GITHUB_TOKEN }}